### PR TITLE
Fix 1837, work around sources with scheme fields not matching typedsource fields

### LINKED ISSUE #1837: planner exception with merge
this looks like an error in the new implementation.
```
Caused by: cascading.flow.planner.PlannerException: could not build flow from assembly: [[_pipe_0-464d65c76b6f+_...][planTypedWrites() @ com.twitter.scalding.Job.validate(Job.sca
la:310)] merged streams must declare the same field names, in the same order, expected: [{1}:0] found: [{?}:UNKNOWN]]
        at cascading.flow.planner.FlowPlanner.handleExceptionDuringPlanning(FlowPlanner.java:578)
        at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:286)
        at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:80)
        at cascading.flow.FlowConnector.connect(FlowConnector.java:459)
        at com.twitter.scalding.ExecutionContext$class.buildFlow(ExecutionContext.scala:86)
        at com.twitter.scalding.ExecutionContext$$anon$1.buildFlow(ExecutionContext.scala:179)
        at com.twitter.scalding.Job$$anonfun$buildFlow$1.apply(Job.scala:287)
        at com.twitter.scalding.Job$$anonfun$buildFlow$1.apply(Job.scala:287)
        at scala.util.Success.flatMap(Try.scala:231)
        at com.twitter.scalding.Job.buildFlow(Job.scala:287)
        at com.stripe.zoolander.parquet.ParquetJob$class.run(ParquetJob.scala:143)
        at com.stripe.zoolander.treasury.LedgerClearingTimeseries.run(LedgerClearingTimeseries.scala:16)
        at com.twitter.scalding.Tool.start$1(Tool.scala:124)
        at com.twitter.scalding.Tool.run(Tool.scala:141)
        at com.twitter.scalding.Tool.run(Tool.scala:68)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at com.twitter.scalding.Tool$.main(Tool.scala:149)
        ... 1 more
Caused by: cascading.pipe.OperatorException: [_pipe_0-464d65c76b6f+_...][planTypedWrites() @ com.twitter.scalding.Job.validate(Job.scala:310)] merged streams must declare the sam
e field names, in the same order, expected: [{1}:0] found: [{?}:UNKNOWN]
        at cascading.pipe.Splice.resolveDeclared(Splice.java:1276)
        at cascading.pipe.Splice.outgoingScopeFor(Splice.java:992)
        at cascading.flow.planner.ElementGraph.resolveFields(ElementGraph.java:628)
        at cascading.flow.planner.ElementGraph.resolveFields(ElementGraph.java:610)
        at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:270)
        ... 16 more
```
Seems like we are somehow merging without being sure they share the same fields.

We need a repro, and then it should be easy to fix.

### PR DESCRIPTION
**Pull request by johnynek**
closes #1837 

The issue is that cascading schemes have fields but so do TypedSources. Nothing requires those to be in sync, but they should be. In the case of ParquetScheme, there are not set Fields `Fields.UNKNOWN`. Since scalding 0.18 has an optimization that removes unneeded maps this exposes the bug we merge an unmapped parquet source with a mapped one.

### CODE REVIEW

File: scalding-parquet-scrooge/src/test/scala/com/twitter/scalding/parquet/scrooge/PlanningTests.scala [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+    flow.getFlowSteps.size
+  }
+
+  // test for https://github.com/twitter/scalding/issues/1837
+  test("merging source plus mapped source works") {
+    val src1 = new FixedPathParquetScrooge[MockThriftStruct]("src1")
+    val src2 = new FixedPathParquetScrooge[MockThriftStruct]("src2")
+
+    val pipe = (TypedPipe.from(src1) ++
+      TypedPipe.from(src2).map(_ => null.asInstanceOf[MockThriftStruct]))
```
Comment (johnynek) [inline scalding-parquet-scrooge/src/test/scala/com/twitter/scalding/parquet/scrooge/PlanningTests.scala:27]: this was actually the only test that could repro the issue.

**Comment by johnynek** [comment]
@ianoc ptal

cc @fwbrasil

**Comment by ianoc** [comment]
lgtm

great work getting a test going

**Comment by fwbrasil** [comment]
LGTM. Thank you!
